// <auto-generated />
using CanteenManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CanteenManagementSystem.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211116210812_AddedMenuDetails")]
    partial class AddedMenuDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CanteenManagementSystem.Models.menuDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("manuAvailbility")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("manuDescription")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("manuImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("manuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("manuType")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("menuPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("vegOrNonVeg")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("menudetails");
                });
#pragma warning restore 612, 618
        }
    }
}
